services:
  yaass:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/yaass/data
    ports:
      - '6969:6969'
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M